name: ci/cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 检查代码仓库
        uses: actions/checkout@v3

      # 设置node.js环境
      - name: 设置Node环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 安装项目依赖
      - name: 安装项目依赖
        run: npm install

      # 构建项目
      - name: 构建项目
        run: npm run build

      # 运行测试
      - name: 运行测试
        run: npm run test

      # 部署到github pages
      - name: 部署
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # 部署到 gh-pages 分支
          folder: dist  # Vite 默认构建输出文件夹为 dist
